version: '3.9'
services:
  nestapp:
    container_name: tetris
    image: tetris/app:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
      - PORT=3000
      - JWT_SECRET=securejwtkey
      - JWT_SECRET_INTERNAL=internaljwtkeysecurityverygoodandhigh
      - URL=http://localhost:4200
      - EMAIL_PASSWORD=tohgshwdtjzywvax
    depends_on:
      - db
    volumes:
      - ./src:/src
    command: npm run start:dev
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}